### ISSUE TITLE
游猴脚本工程化搭建交流

### ISSUE THREAD

**Issue by yukinotech** [miaolapd/KF_Online_Assistant#1]
你好，喵拉布丁先生/女士(假正经)

我粗略的看了KFOnline的源码，有些问题想交流一下。

本人前端开发资历尚浅，如果有说错的地方，请指出，还请多多包涵。

KFOnline开发时使用glup构建，浏览器端使用browserify，进行模块导入。生成dist文件，然后将dist文件考入油猴脚本，完成搭建。

这样就有一个开发的问题，在开发时，不等不改动一些地方，然后在gulp一下，生成dist，再复制进游猴脚本，完成一次更新。（这个地方是我猜测的，不知道你是怎么处理这个问题的，有更好的开发方式）

这样开发就会比较繁琐，因此我参考了一些其他的游猴脚本的构建方式，发现了一个不错的开发方式，想和你交流一下。

1.首先在本地启用一个nodejs服务器，例如express，将一个静态js文件挂载到静态目录下。
这个js文件就作为游猴脚本的入口文件。

2.游猴脚本中的代码可以固定不变，即只需要实现，在底部body标签上端插入script标签，src指向静态目录下的js文件。

3.这样就只用在这一个入口js文件中引入其他模块，进行开发。每次更新代码，直接刷新油猴脚本运行的页面，就能更新代码。这样开发效率会更高。

上述是简单的原理，实际开发就会发现，这个思想和webpack比较相似，即一个入口js，导入所有所需要的文件，可以进行压缩和打包。

并且使用上了webpack，就可以使用react或vue进行现代化组件的构建和打包，搭建更好维护的组件。

上述方案唯一的缺点是，用户部署时如果也使用入口文件的方式，需要在公网搭建一个静态服务器储存这个静态入口js文件。

但是这个问题是可以解决的。可以写一个js脚本将游猴的头部和webpack 的build的dist入口文件拼装起来，生成最终的油猴脚本，最后发布。

以上是我的想法，希望能和你交流一下。

**Comment by miaolapd** [comment]
嗯，我用的方法和你说的有部分相似
我是写了个用来在底部body插入script标签的油猴脚本，将本地服务器上的KFOL助手插入到KF页面中
然后编写代码的时候，就自动gulp一下，生成dist文件，刷新页面后就可以生效了
这个是我几年前刚开始学gulp时想到的一个方法（不管是那时候还是现在我对前端开发其实都算不上很了解，充其量也只是会用而已）
至于现在已经没多少精力开发KFOL助手了，也就不想再做什么大的改动了

你说的这种倒是更好的方式，非常感谢你的建议，以后要是再有机会开发新的油猴脚本的话，可以试试

**Comment by yukinotech** [comment]
感谢你的回复，看来开发的时候都是通过部署本地服务器实现在线更新的。

学到了(手动滑稽)。

能冒昧的问一下dalao现在还在写码吗？具体是前端，后端还是运维之类的？
我现在(未毕业)准备向前端发展，但是也想了解一下其他职位，想听一下前辈的职位分析和建议，谢谢。

**Comment by miaolapd** [comment]
其实我也没什么能给你建议的，我一开始是搞PHP的，后面又去搞.NET，前端只是顺便做的
不过掌握些后端的技能总归是好事，而且node.js也可以用来写后端了，可以考虑往全栈方向发展
现在我也没怎么写代码了，编程只是闲暇时的兴趣而已
